### ISSUE TITLE
Program crashes upon keyboard-based change of axes limits

### ISSUE THREAD

**Issue by khoehlein** [wavestoweather/PCViewer#1]
Automatic axes limits are set to -0.000101 (min) to 0 (max). When putting the cursor in the min field and deleting digits from the end of the entry with backspace (ie. min = -0.000101 -> min = -0.00010 -> min = -0.0001), the program crashes once the last non-zero decimal digit is deleted (ie. crash at min = -0.000). No crash is observed if the max is set to -0.000101.

**Comment by Lachei** [comment]
Not encountered in the newer versions of the PCViewer_new
