### ISSUE TITLE
No axis ticks appear upon change of axes limits and program crashes when activating axis histograms

### ISSUE THREAD

**Issue by khoehlein** [wavestoweather/PCViewer#2]
Axis is drawn with automatic limits min=-1.4, max=1.212e+4. Upon resetting min to 10000, the axis remains blank without any axis ticks. 

Activating heatmap axis histograms in the setting 10000 to 1.212e+4 leads to crash.

Version: Windows binary of backend_rework, 2023-02-24.

**Comment by Lachei** [comment]
Crash on histogram activation is fixed in 25c5600fd13d2338f1321c446a8e9ca893c3a3da. 
However i could not yet reproduce the other bugs.
